// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir500

import (
	"encoding/json"
	"fmt"
	"strings"
)

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// ActionParticipantType is documented here http://hl7.org/fhir/ValueSet/action-participant-type
type ActionParticipantType int

const (
	ActionParticipantTypeCareteam ActionParticipantType = iota
	ActionParticipantTypeDevice
	ActionParticipantTypeGroup
	ActionParticipantTypeHealthcareservice
	ActionParticipantTypeLocation
	ActionParticipantTypeOrganization
	ActionParticipantTypePatient
	ActionParticipantTypePractitioner
	ActionParticipantTypePractitionerrole
	ActionParticipantTypeRelatedperson
)

func (code ActionParticipantType) MarshalJSON() ([]byte, error) {
	return json.Marshal(code.Code())
}
func (code *ActionParticipantType) UnmarshalJSON(json []byte) error {
	s := strings.Trim(string(json), "\"")
	switch s {
	case "careteam":
		*code = ActionParticipantTypeCareteam
	case "device":
		*code = ActionParticipantTypeDevice
	case "group":
		*code = ActionParticipantTypeGroup
	case "healthcareservice":
		*code = ActionParticipantTypeHealthcareservice
	case "location":
		*code = ActionParticipantTypeLocation
	case "organization":
		*code = ActionParticipantTypeOrganization
	case "patient":
		*code = ActionParticipantTypePatient
	case "practitioner":
		*code = ActionParticipantTypePractitioner
	case "practitionerrole":
		*code = ActionParticipantTypePractitionerrole
	case "relatedperson":
		*code = ActionParticipantTypeRelatedperson
	default:
		return fmt.Errorf("unknown ActionParticipantType code `%s`", s)
	}
	return nil
}
func (code ActionParticipantType) String() string {
	return code.Code()
}
func (code ActionParticipantType) Code() string {
	switch code {
	case ActionParticipantTypeCareteam:
		return "careteam"
	case ActionParticipantTypeDevice:
		return "device"
	case ActionParticipantTypeGroup:
		return "group"
	case ActionParticipantTypeHealthcareservice:
		return "healthcareservice"
	case ActionParticipantTypeLocation:
		return "location"
	case ActionParticipantTypeOrganization:
		return "organization"
	case ActionParticipantTypePatient:
		return "patient"
	case ActionParticipantTypePractitioner:
		return "practitioner"
	case ActionParticipantTypePractitionerrole:
		return "practitionerrole"
	case ActionParticipantTypeRelatedperson:
		return "relatedperson"
	}
	return "<unknown>"
}
func (code ActionParticipantType) Display() string {
	switch code {
	case ActionParticipantTypeCareteam:
		return "CareTeam"
	case ActionParticipantTypeDevice:
		return "Device"
	case ActionParticipantTypeGroup:
		return "Group"
	case ActionParticipantTypeHealthcareservice:
		return "HealthcareService"
	case ActionParticipantTypeLocation:
		return "Location"
	case ActionParticipantTypeOrganization:
		return "Organization"
	case ActionParticipantTypePatient:
		return "Patient"
	case ActionParticipantTypePractitioner:
		return "Practitioner"
	case ActionParticipantTypePractitionerrole:
		return "PractitionerRole"
	case ActionParticipantTypeRelatedperson:
		return "RelatedPerson"
	}
	return "<unknown>"
}
func (code ActionParticipantType) Definition() string {
	switch code {
	case ActionParticipantTypeCareteam:
		return "The participant is a care team caring for the patient under evaluation."
	case ActionParticipantTypeDevice:
		return "The participant is a system or device used in the care of the patient."
	case ActionParticipantTypeGroup:
		return "The participant is a group of participants involved in the care of the patient."
	case ActionParticipantTypeHealthcareservice:
		return "The participant is an institution that can provide the given healthcare service used in the care of the patient."
	case ActionParticipantTypeLocation:
		return "The participant is a location involved in the care of the patient."
	case ActionParticipantTypeOrganization:
		return "The participant is an organization involved in the care of the patient."
	case ActionParticipantTypePatient:
		return "The participant is the patient under evaluation."
	case ActionParticipantTypePractitioner:
		return "The participant is a practitioner involved in the patient's care."
	case ActionParticipantTypePractitionerrole:
		return "The participant is a particular practitioner role involved in the patient's care."
	case ActionParticipantTypeRelatedperson:
		return "The participant is a person related to the patient."
	}
	return "<unknown>"
}
