// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir500

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// ArtifactAssessment is documented here http://hl7.org/fhir/StructureDefinition/ArtifactAssessment
type ArtifactAssessment struct {
	ID                *string                           `json:"id,omitempty"`
	Meta              *Meta                             `json:"meta,omitempty"`
	ImplicitRules     *string                           `json:"implicitRules,omitempty"`
	Language          *string                           `json:"language,omitempty"`
	Text              *Narrative                        `json:"text,omitempty"`
	Extension         []Extension                       `json:"extension,omitempty"`
	ModifierExtension []Extension                       `json:"modifierExtension,omitempty"`
	Identifier        []Identifier                      `json:"identifier,omitempty"`
	Title             *string                           `json:"title,omitempty"`
	CiteAsReference   *Reference                        `json:"citeAsReference,omitempty"`
	CiteAsMarkdown    *string                           `json:"citeAsMarkdown,omitempty"`
	Date              *string                           `json:"date,omitempty"`
	Copyright         *string                           `json:"copyright,omitempty"`
	ApprovalDate      *string                           `json:"approvalDate,omitempty"`
	LastReviewDate    *string                           `json:"lastReviewDate,omitempty"`
	ArtifactReference *Reference                        `json:"artifactReference,omitempty"`
	ArtifactCanonical *string                           `json:"artifactCanonical,omitempty"`
	ArtifactUri       *string                           `json:"artifactUri,omitempty"`
	Content           []ArtifactAssessmentContent       `json:"content,omitempty"`
	WorkflowStatus    *ArtifactAssessmentWorkflowStatus `json:"workflowStatus,omitempty"`
	Disposition       *ArtifactAssessmentDisposition    `json:"disposition,omitempty"`
}
type ArtifactAssessmentContent struct {
	ID                *string                            `json:"id,omitempty"`
	Extension         []Extension                        `json:"extension,omitempty"`
	ModifierExtension []Extension                        `json:"modifierExtension,omitempty"`
	InformationType   *ArtifactAssessmentInformationType `json:"informationType,omitempty"`
	Summary           *string                            `json:"summary,omitempty"`
	Type              *CodeableConcept                   `json:"type,omitempty"`
	Classifier        []CodeableConcept                  `json:"classifier,omitempty"`
	Quantity          *Quantity                          `json:"quantity,omitempty"`
	Author            *Reference                         `json:"author,omitempty"`
	Path              []string                           `json:"path,omitempty"`
	RelatedArtifact   []RelatedArtifact                  `json:"relatedArtifact,omitempty"`
	FreeToShare       *bool                              `json:"freeToShare,omitempty"`
	Component         []ArtifactAssessmentContent        `json:"component,omitempty"`
}
type OtherArtifactAssessment ArtifactAssessment

// MarshalJSON marshals the given ArtifactAssessment as JSON into a byte slice
func (r ArtifactAssessment) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherArtifactAssessment
		ResourceType string `json:"resourceType"`
	}{
		OtherArtifactAssessment: OtherArtifactAssessment(r),
		ResourceType:            "ArtifactAssessment",
	})
}

// UnmarshalArtifactAssessment unmarshals a ArtifactAssessment.
func UnmarshalArtifactAssessment(b []byte) (ArtifactAssessment, error) {
	var artifactAssessment ArtifactAssessment
	if err := json.Unmarshal(b, &artifactAssessment); err != nil {
		return artifactAssessment, err
	}
	return artifactAssessment, nil
}
