// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir500

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// Claim is documented here http://hl7.org/fhir/StructureDefinition/Claim
type Claim struct {
	ID                    *string                      `json:"id,omitempty"`
	Meta                  *Meta                        `json:"meta,omitempty"`
	ImplicitRules         *string                      `json:"implicitRules,omitempty"`
	Language              *string                      `json:"language,omitempty"`
	Text                  *Narrative                   `json:"text,omitempty"`
	Extension             []Extension                  `json:"extension,omitempty"`
	ModifierExtension     []Extension                  `json:"modifierExtension,omitempty"`
	Identifier            []Identifier                 `json:"identifier,omitempty"`
	TraceNumber           []Identifier                 `json:"traceNumber,omitempty"`
	Status                FinancialResourceStatusCodes `json:"status"`
	Type                  CodeableConcept              `json:"type"`
	SubType               *CodeableConcept             `json:"subType,omitempty"`
	Use                   Use                          `json:"use"`
	Patient               Reference                    `json:"patient"`
	BillablePeriod        *Period                      `json:"billablePeriod,omitempty"`
	Created               string                       `json:"created"`
	Enterer               *Reference                   `json:"enterer,omitempty"`
	Insurer               *Reference                   `json:"insurer,omitempty"`
	Provider              *Reference                   `json:"provider,omitempty"`
	Priority              *CodeableConcept             `json:"priority,omitempty"`
	FundsReserve          *CodeableConcept             `json:"fundsReserve,omitempty"`
	Related               []ClaimRelated               `json:"related,omitempty"`
	Prescription          *Reference                   `json:"prescription,omitempty"`
	OriginalPrescription  *Reference                   `json:"originalPrescription,omitempty"`
	Payee                 *ClaimPayee                  `json:"payee,omitempty"`
	Referral              *Reference                   `json:"referral,omitempty"`
	Encounter             []Reference                  `json:"encounter,omitempty"`
	Facility              *Reference                   `json:"facility,omitempty"`
	DiagnosisRelatedGroup *CodeableConcept             `json:"diagnosisRelatedGroup,omitempty"`
	Event                 []ClaimEvent                 `json:"event,omitempty"`
	CareTeam              []ClaimCareTeam              `json:"careTeam,omitempty"`
	SupportingInfo        []ClaimSupportingInfo        `json:"supportingInfo,omitempty"`
	Diagnosis             []ClaimDiagnosis             `json:"diagnosis,omitempty"`
	Procedure             []ClaimProcedure             `json:"procedure,omitempty"`
	Insurance             []ClaimInsurance             `json:"insurance,omitempty"`
	Accident              *ClaimAccident               `json:"accident,omitempty"`
	PatientPaid           *Money                       `json:"patientPaid,omitempty"`
	Item                  []ClaimItem                  `json:"item,omitempty"`
	Total                 *Money                       `json:"total,omitempty"`
}
type ClaimRelated struct {
	ID                *string          `json:"id,omitempty"`
	Extension         []Extension      `json:"extension,omitempty"`
	ModifierExtension []Extension      `json:"modifierExtension,omitempty"`
	Claim             *Reference       `json:"claim,omitempty"`
	Relationship      *CodeableConcept `json:"relationship,omitempty"`
	Reference         *Identifier      `json:"reference,omitempty"`
}
type ClaimPayee struct {
	ID                *string         `json:"id,omitempty"`
	Extension         []Extension     `json:"extension,omitempty"`
	ModifierExtension []Extension     `json:"modifierExtension,omitempty"`
	Type              CodeableConcept `json:"type"`
	Party             *Reference      `json:"party,omitempty"`
}
type ClaimEvent struct {
	ID                *string         `json:"id,omitempty"`
	Extension         []Extension     `json:"extension,omitempty"`
	ModifierExtension []Extension     `json:"modifierExtension,omitempty"`
	Type              CodeableConcept `json:"type"`
	WhenDateTime      *string         `json:"whenDateTime,omitempty"`
	WhenPeriod        *Period         `json:"whenPeriod,omitempty"`
}
type ClaimCareTeam struct {
	ID                *string          `json:"id,omitempty"`
	Extension         []Extension      `json:"extension,omitempty"`
	ModifierExtension []Extension      `json:"modifierExtension,omitempty"`
	Sequence          int              `json:"sequence"`
	Provider          Reference        `json:"provider"`
	Responsible       *bool            `json:"responsible,omitempty"`
	Role              *CodeableConcept `json:"role,omitempty"`
	Specialty         *CodeableConcept `json:"specialty,omitempty"`
}
type ClaimSupportingInfo struct {
	ID                *string          `json:"id,omitempty"`
	Extension         []Extension      `json:"extension,omitempty"`
	ModifierExtension []Extension      `json:"modifierExtension,omitempty"`
	Sequence          int              `json:"sequence"`
	Category          CodeableConcept  `json:"category"`
	Code              *CodeableConcept `json:"code,omitempty"`
	TimingDate        *string          `json:"timingDate,omitempty"`
	TimingPeriod      *Period          `json:"timingPeriod,omitempty"`
	ValueBoolean      *bool            `json:"valueBoolean,omitempty"`
	ValueString       *string          `json:"valueString,omitempty"`
	ValueQuantity     *Quantity        `json:"valueQuantity,omitempty"`
	ValueAttachment   *Attachment      `json:"valueAttachment,omitempty"`
	ValueReference    *Reference       `json:"valueReference,omitempty"`
	ValueIdentifier   *Identifier      `json:"valueIdentifier,omitempty"`
	Reason            *CodeableConcept `json:"reason,omitempty"`
}
type ClaimDiagnosis struct {
	ID                       *string           `json:"id,omitempty"`
	Extension                []Extension       `json:"extension,omitempty"`
	ModifierExtension        []Extension       `json:"modifierExtension,omitempty"`
	Sequence                 int               `json:"sequence"`
	DiagnosisCodeableConcept *CodeableConcept  `json:"diagnosisCodeableConcept,omitempty"`
	DiagnosisReference       *Reference        `json:"diagnosisReference,omitempty"`
	Type                     []CodeableConcept `json:"type,omitempty"`
	OnAdmission              *CodeableConcept  `json:"onAdmission,omitempty"`
}
type ClaimProcedure struct {
	ID                       *string           `json:"id,omitempty"`
	Extension                []Extension       `json:"extension,omitempty"`
	ModifierExtension        []Extension       `json:"modifierExtension,omitempty"`
	Sequence                 int               `json:"sequence"`
	Type                     []CodeableConcept `json:"type,omitempty"`
	Date                     *string           `json:"date,omitempty"`
	ProcedureCodeableConcept *CodeableConcept  `json:"procedureCodeableConcept,omitempty"`
	ProcedureReference       *Reference        `json:"procedureReference,omitempty"`
	Udi                      []Reference       `json:"udi,omitempty"`
}
type ClaimInsurance struct {
	ID                  *string     `json:"id,omitempty"`
	Extension           []Extension `json:"extension,omitempty"`
	ModifierExtension   []Extension `json:"modifierExtension,omitempty"`
	Sequence            int         `json:"sequence"`
	Focal               bool        `json:"focal"`
	Identifier          *Identifier `json:"identifier,omitempty"`
	Coverage            Reference   `json:"coverage"`
	BusinessArrangement *string     `json:"businessArrangement,omitempty"`
	PreAuthRef          []string    `json:"preAuthRef,omitempty"`
	ClaimResponse       *Reference  `json:"claimResponse,omitempty"`
}
type ClaimAccident struct {
	ID                *string          `json:"id,omitempty"`
	Extension         []Extension      `json:"extension,omitempty"`
	ModifierExtension []Extension      `json:"modifierExtension,omitempty"`
	Date              string           `json:"date"`
	Type              *CodeableConcept `json:"type,omitempty"`
	LocationAddress   *Address         `json:"locationAddress,omitempty"`
	LocationReference *Reference       `json:"locationReference,omitempty"`
}
type ClaimItem struct {
	ID                      *string             `json:"id,omitempty"`
	Extension               []Extension         `json:"extension,omitempty"`
	ModifierExtension       []Extension         `json:"modifierExtension,omitempty"`
	Sequence                int                 `json:"sequence"`
	TraceNumber             []Identifier        `json:"traceNumber,omitempty"`
	CareTeamSequence        []int               `json:"careTeamSequence,omitempty"`
	DiagnosisSequence       []int               `json:"diagnosisSequence,omitempty"`
	ProcedureSequence       []int               `json:"procedureSequence,omitempty"`
	InformationSequence     []int               `json:"informationSequence,omitempty"`
	Revenue                 *CodeableConcept    `json:"revenue,omitempty"`
	Category                *CodeableConcept    `json:"category,omitempty"`
	ProductOrService        *CodeableConcept    `json:"productOrService,omitempty"`
	ProductOrServiceEnd     *CodeableConcept    `json:"productOrServiceEnd,omitempty"`
	Request                 []Reference         `json:"request,omitempty"`
	Modifier                []CodeableConcept   `json:"modifier,omitempty"`
	ProgramCode             []CodeableConcept   `json:"programCode,omitempty"`
	ServicedDate            *string             `json:"servicedDate,omitempty"`
	ServicedPeriod          *Period             `json:"servicedPeriod,omitempty"`
	LocationCodeableConcept *CodeableConcept    `json:"locationCodeableConcept,omitempty"`
	LocationAddress         *Address            `json:"locationAddress,omitempty"`
	LocationReference       *Reference          `json:"locationReference,omitempty"`
	PatientPaid             *Money              `json:"patientPaid,omitempty"`
	Quantity                *Quantity           `json:"quantity,omitempty"`
	UnitPrice               *Money              `json:"unitPrice,omitempty"`
	Factor                  *json.Number        `json:"factor,omitempty"`
	Tax                     *Money              `json:"tax,omitempty"`
	Net                     *Money              `json:"net,omitempty"`
	Udi                     []Reference         `json:"udi,omitempty"`
	BodySite                []ClaimItemBodySite `json:"bodySite,omitempty"`
	Encounter               []Reference         `json:"encounter,omitempty"`
	Detail                  []ClaimItemDetail   `json:"detail,omitempty"`
}
type ClaimItemBodySite struct {
	ID                *string             `json:"id,omitempty"`
	Extension         []Extension         `json:"extension,omitempty"`
	ModifierExtension []Extension         `json:"modifierExtension,omitempty"`
	Site              []CodeableReference `json:"site"`
	SubSite           []CodeableConcept   `json:"subSite,omitempty"`
}
type ClaimItemDetail struct {
	ID                  *string                    `json:"id,omitempty"`
	Extension           []Extension                `json:"extension,omitempty"`
	ModifierExtension   []Extension                `json:"modifierExtension,omitempty"`
	Sequence            int                        `json:"sequence"`
	TraceNumber         []Identifier               `json:"traceNumber,omitempty"`
	Revenue             *CodeableConcept           `json:"revenue,omitempty"`
	Category            *CodeableConcept           `json:"category,omitempty"`
	ProductOrService    *CodeableConcept           `json:"productOrService,omitempty"`
	ProductOrServiceEnd *CodeableConcept           `json:"productOrServiceEnd,omitempty"`
	Modifier            []CodeableConcept          `json:"modifier,omitempty"`
	ProgramCode         []CodeableConcept          `json:"programCode,omitempty"`
	PatientPaid         *Money                     `json:"patientPaid,omitempty"`
	Quantity            *Quantity                  `json:"quantity,omitempty"`
	UnitPrice           *Money                     `json:"unitPrice,omitempty"`
	Factor              *json.Number               `json:"factor,omitempty"`
	Tax                 *Money                     `json:"tax,omitempty"`
	Net                 *Money                     `json:"net,omitempty"`
	Udi                 []Reference                `json:"udi,omitempty"`
	SubDetail           []ClaimItemDetailSubDetail `json:"subDetail,omitempty"`
}
type ClaimItemDetailSubDetail struct {
	ID                  *string           `json:"id,omitempty"`
	Extension           []Extension       `json:"extension,omitempty"`
	ModifierExtension   []Extension       `json:"modifierExtension,omitempty"`
	Sequence            int               `json:"sequence"`
	TraceNumber         []Identifier      `json:"traceNumber,omitempty"`
	Revenue             *CodeableConcept  `json:"revenue,omitempty"`
	Category            *CodeableConcept  `json:"category,omitempty"`
	ProductOrService    *CodeableConcept  `json:"productOrService,omitempty"`
	ProductOrServiceEnd *CodeableConcept  `json:"productOrServiceEnd,omitempty"`
	Modifier            []CodeableConcept `json:"modifier,omitempty"`
	ProgramCode         []CodeableConcept `json:"programCode,omitempty"`
	PatientPaid         *Money            `json:"patientPaid,omitempty"`
	Quantity            *Quantity         `json:"quantity,omitempty"`
	UnitPrice           *Money            `json:"unitPrice,omitempty"`
	Factor              *json.Number      `json:"factor,omitempty"`
	Tax                 *Money            `json:"tax,omitempty"`
	Net                 *Money            `json:"net,omitempty"`
	Udi                 []Reference       `json:"udi,omitempty"`
}
type OtherClaim Claim

// MarshalJSON marshals the given Claim as JSON into a byte slice
func (r Claim) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherClaim
		ResourceType string `json:"resourceType"`
	}{
		OtherClaim:   OtherClaim(r),
		ResourceType: "Claim",
	})
}

// UnmarshalClaim unmarshals a Claim.
func UnmarshalClaim(b []byte) (Claim, error) {
	var claim Claim
	if err := json.Unmarshal(b, &claim); err != nil {
		return claim, err
	}
	return claim, nil
}
