// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir500

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// FormularyItem is documented here http://hl7.org/fhir/StructureDefinition/FormularyItem
type FormularyItem struct {
	ID                *string                   `json:"id,omitempty"`
	Meta              *Meta                     `json:"meta,omitempty"`
	ImplicitRules     *string                   `json:"implicitRules,omitempty"`
	Language          *string                   `json:"language,omitempty"`
	Text              *Narrative                `json:"text,omitempty"`
	Extension         []Extension               `json:"extension,omitempty"`
	ModifierExtension []Extension               `json:"modifierExtension,omitempty"`
	Identifier        []Identifier              `json:"identifier,omitempty"`
	Code              *CodeableConcept          `json:"code,omitempty"`
	Status            *FormularyItemStatusCodes `json:"status,omitempty"`
}
type OtherFormularyItem FormularyItem

// MarshalJSON marshals the given FormularyItem as JSON into a byte slice
func (r FormularyItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherFormularyItem
		ResourceType string `json:"resourceType"`
	}{
		OtherFormularyItem: OtherFormularyItem(r),
		ResourceType:       "FormularyItem",
	})
}

// UnmarshalFormularyItem unmarshals a FormularyItem.
func UnmarshalFormularyItem(b []byte) (FormularyItem, error) {
	var formularyItem FormularyItem
	if err := json.Unmarshal(b, &formularyItem); err != nil {
		return formularyItem, err
	}
	return formularyItem, nil
}
