// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir500

import (
	"encoding/json"
	"fmt"
	"strings"
)

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// GroupType is documented here http://hl7.org/fhir/ValueSet/group-type
type GroupType int

const (
	GroupTypePerson GroupType = iota
	GroupTypeAnimal
	GroupTypePractitioner
	GroupTypeDevice
	GroupTypeCareteam
	GroupTypeHealthcareservice
	GroupTypeLocation
	GroupTypeOrganization
	GroupTypeRelatedperson
	GroupTypeSpecimen
)

func (code GroupType) MarshalJSON() ([]byte, error) {
	return json.Marshal(code.Code())
}
func (code *GroupType) UnmarshalJSON(json []byte) error {
	s := strings.Trim(string(json), "\"")
	switch s {
	case "person":
		*code = GroupTypePerson
	case "animal":
		*code = GroupTypeAnimal
	case "practitioner":
		*code = GroupTypePractitioner
	case "device":
		*code = GroupTypeDevice
	case "careteam":
		*code = GroupTypeCareteam
	case "healthcareservice":
		*code = GroupTypeHealthcareservice
	case "location":
		*code = GroupTypeLocation
	case "organization":
		*code = GroupTypeOrganization
	case "relatedperson":
		*code = GroupTypeRelatedperson
	case "specimen":
		*code = GroupTypeSpecimen
	default:
		return fmt.Errorf("unknown GroupType code `%s`", s)
	}
	return nil
}
func (code GroupType) String() string {
	return code.Code()
}
func (code GroupType) Code() string {
	switch code {
	case GroupTypePerson:
		return "person"
	case GroupTypeAnimal:
		return "animal"
	case GroupTypePractitioner:
		return "practitioner"
	case GroupTypeDevice:
		return "device"
	case GroupTypeCareteam:
		return "careteam"
	case GroupTypeHealthcareservice:
		return "healthcareservice"
	case GroupTypeLocation:
		return "location"
	case GroupTypeOrganization:
		return "organization"
	case GroupTypeRelatedperson:
		return "relatedperson"
	case GroupTypeSpecimen:
		return "specimen"
	}
	return "<unknown>"
}
func (code GroupType) Display() string {
	switch code {
	case GroupTypePerson:
		return "Person"
	case GroupTypeAnimal:
		return "Animal"
	case GroupTypePractitioner:
		return "Practitioner"
	case GroupTypeDevice:
		return "Device"
	case GroupTypeCareteam:
		return "CareTeam"
	case GroupTypeHealthcareservice:
		return "HealthcareService"
	case GroupTypeLocation:
		return "Location"
	case GroupTypeOrganization:
		return "Organization"
	case GroupTypeRelatedperson:
		return "RelatedPerson"
	case GroupTypeSpecimen:
		return "Specimen"
	}
	return "<unknown>"
}
func (code GroupType) Definition() string {
	switch code {
	case GroupTypePerson:
		return "Group contains \"person\" Patient resources."
	case GroupTypeAnimal:
		return "Group contains \"animal\" Patient resources."
	case GroupTypePractitioner:
		return "Group contains healthcare practitioner resources (Practitioner or PractitionerRole)."
	case GroupTypeDevice:
		return "Group contains Device resources."
	case GroupTypeCareteam:
		return "Group contains CareTeam resources."
	case GroupTypeHealthcareservice:
		return "Group contains HealthcareService resources."
	case GroupTypeLocation:
		return "Group contains Location resources."
	case GroupTypeOrganization:
		return "Group contains Organization resources."
	case GroupTypeRelatedperson:
		return "Group contains RelatedPerson resources."
	case GroupTypeSpecimen:
		return "Group contains Specimen resources."
	}
	return "<unknown>"
}
