// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir500

import (
	"encoding/json"
	"fmt"
	"strings"
)

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// MedicationRequestIntent is documented here http://hl7.org/fhir/ValueSet/medicationrequest-intent
type MedicationRequestIntent int

const (
	MedicationRequestIntentProposal MedicationRequestIntent = iota
	MedicationRequestIntentPlan
	MedicationRequestIntentOrder
	MedicationRequestIntentOriginalOrder
	MedicationRequestIntentReflexOrder
	MedicationRequestIntentFillerOrder
	MedicationRequestIntentInstanceOrder
	MedicationRequestIntentOption
)

func (code MedicationRequestIntent) MarshalJSON() ([]byte, error) {
	return json.Marshal(code.Code())
}
func (code *MedicationRequestIntent) UnmarshalJSON(json []byte) error {
	s := strings.Trim(string(json), "\"")
	switch s {
	case "proposal":
		*code = MedicationRequestIntentProposal
	case "plan":
		*code = MedicationRequestIntentPlan
	case "order":
		*code = MedicationRequestIntentOrder
	case "original-order":
		*code = MedicationRequestIntentOriginalOrder
	case "reflex-order":
		*code = MedicationRequestIntentReflexOrder
	case "filler-order":
		*code = MedicationRequestIntentFillerOrder
	case "instance-order":
		*code = MedicationRequestIntentInstanceOrder
	case "option":
		*code = MedicationRequestIntentOption
	default:
		return fmt.Errorf("unknown MedicationRequestIntent code `%s`", s)
	}
	return nil
}
func (code MedicationRequestIntent) String() string {
	return code.Code()
}
func (code MedicationRequestIntent) Code() string {
	switch code {
	case MedicationRequestIntentProposal:
		return "proposal"
	case MedicationRequestIntentPlan:
		return "plan"
	case MedicationRequestIntentOrder:
		return "order"
	case MedicationRequestIntentOriginalOrder:
		return "original-order"
	case MedicationRequestIntentReflexOrder:
		return "reflex-order"
	case MedicationRequestIntentFillerOrder:
		return "filler-order"
	case MedicationRequestIntentInstanceOrder:
		return "instance-order"
	case MedicationRequestIntentOption:
		return "option"
	}
	return "<unknown>"
}
func (code MedicationRequestIntent) Display() string {
	switch code {
	case MedicationRequestIntentProposal:
		return "Proposal"
	case MedicationRequestIntentPlan:
		return "Plan"
	case MedicationRequestIntentOrder:
		return "Order"
	case MedicationRequestIntentOriginalOrder:
		return "Original Order"
	case MedicationRequestIntentReflexOrder:
		return "Reflex Order"
	case MedicationRequestIntentFillerOrder:
		return "Filler Order"
	case MedicationRequestIntentInstanceOrder:
		return "Instance Order"
	case MedicationRequestIntentOption:
		return "Option"
	}
	return "<unknown>"
}
func (code MedicationRequestIntent) Definition() string {
	switch code {
	case MedicationRequestIntentProposal:
		return "The request is a suggestion made by someone/something that doesn't have an intention to ensure it occurs and without providing an authorization to act"
	case MedicationRequestIntentPlan:
		return "The request represents an intention to ensure something occurs without providing an authorization for others to act."
	case MedicationRequestIntentOrder:
		return "The request represents a request/demand and authorization for action"
	case MedicationRequestIntentOriginalOrder:
		return "The request represents the original authorization for the medication request."
	case MedicationRequestIntentReflexOrder:
		return "The request represents an automatically generated supplemental authorization for action based on a parent authorization together with initial results of the action taken against that parent authorization.."
	case MedicationRequestIntentFillerOrder:
		return "The request represents the view of an authorization instantiated by a fulfilling system representing the details of the fulfiller's intention to act upon a submitted order."
	case MedicationRequestIntentInstanceOrder:
		return "The request represents an instance for the particular order and is used to generate a schedule of requests on a medication administration record (MAR)."
	case MedicationRequestIntentOption:
		return "The request represents a component or option for a RequestOrchestration that establishes timing, conditionality and/or  other constraints among a set of requests."
	}
	return "<unknown>"
}
