// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir500

import (
	"encoding/json"
	"fmt"
	"strings"
)

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// PermissionStatus is documented here http://hl7.org/fhir/ValueSet/permission-status
type PermissionStatus int

const (
	PermissionStatusActive PermissionStatus = iota
	PermissionStatusEnteredInError
	PermissionStatusDraft
	PermissionStatusRejected
)

func (code PermissionStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(code.Code())
}
func (code *PermissionStatus) UnmarshalJSON(json []byte) error {
	s := strings.Trim(string(json), "\"")
	switch s {
	case "active":
		*code = PermissionStatusActive
	case "entered-in-error":
		*code = PermissionStatusEnteredInError
	case "draft":
		*code = PermissionStatusDraft
	case "rejected":
		*code = PermissionStatusRejected
	default:
		return fmt.Errorf("unknown PermissionStatus code `%s`", s)
	}
	return nil
}
func (code PermissionStatus) String() string {
	return code.Code()
}
func (code PermissionStatus) Code() string {
	switch code {
	case PermissionStatusActive:
		return "active"
	case PermissionStatusEnteredInError:
		return "entered-in-error"
	case PermissionStatusDraft:
		return "draft"
	case PermissionStatusRejected:
		return "rejected"
	}
	return "<unknown>"
}
func (code PermissionStatus) Display() string {
	switch code {
	case PermissionStatusActive:
		return "Active"
	case PermissionStatusEnteredInError:
		return "Entered in Error"
	case PermissionStatusDraft:
		return "Draft"
	case PermissionStatusRejected:
		return "Rejected"
	}
	return "<unknown>"
}
func (code PermissionStatus) Definition() string {
	switch code {
	case PermissionStatusActive:
		return "Permission is given."
	case PermissionStatusEnteredInError:
		return "Permission was entered in error and is not active."
	case PermissionStatusDraft:
		return "Permission is being defined."
	case PermissionStatusRejected:
		return "Permission not granted."
	}
	return "<unknown>"
}
