// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir500

import (
	"encoding/json"
	"fmt"
	"strings"
)

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// ProvenanceEntityRole is documented here http://hl7.org/fhir/ValueSet/provenance-entity-role
type ProvenanceEntityRole int

const (
	ProvenanceEntityRoleRevision ProvenanceEntityRole = iota
	ProvenanceEntityRoleQuotation
	ProvenanceEntityRoleSource
	ProvenanceEntityRoleInstantiates
	ProvenanceEntityRoleRemoval
)

func (code ProvenanceEntityRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(code.Code())
}
func (code *ProvenanceEntityRole) UnmarshalJSON(json []byte) error {
	s := strings.Trim(string(json), "\"")
	switch s {
	case "revision":
		*code = ProvenanceEntityRoleRevision
	case "quotation":
		*code = ProvenanceEntityRoleQuotation
	case "source":
		*code = ProvenanceEntityRoleSource
	case "instantiates":
		*code = ProvenanceEntityRoleInstantiates
	case "removal":
		*code = ProvenanceEntityRoleRemoval
	default:
		return fmt.Errorf("unknown ProvenanceEntityRole code `%s`", s)
	}
	return nil
}
func (code ProvenanceEntityRole) String() string {
	return code.Code()
}
func (code ProvenanceEntityRole) Code() string {
	switch code {
	case ProvenanceEntityRoleRevision:
		return "revision"
	case ProvenanceEntityRoleQuotation:
		return "quotation"
	case ProvenanceEntityRoleSource:
		return "source"
	case ProvenanceEntityRoleInstantiates:
		return "instantiates"
	case ProvenanceEntityRoleRemoval:
		return "removal"
	}
	return "<unknown>"
}
func (code ProvenanceEntityRole) Display() string {
	switch code {
	case ProvenanceEntityRoleRevision:
		return "Revision"
	case ProvenanceEntityRoleQuotation:
		return "Quotation"
	case ProvenanceEntityRoleSource:
		return "Source"
	case ProvenanceEntityRoleInstantiates:
		return "Instantiates"
	case ProvenanceEntityRoleRemoval:
		return "Removal"
	}
	return "<unknown>"
}
func (code ProvenanceEntityRole) Definition() string {
	switch code {
	case ProvenanceEntityRoleRevision:
		return "An entity that is used by the activity to produce a new version of that entity."
	case ProvenanceEntityRoleQuotation:
		return "An entity that is copied in full or part by an agent that is not the author of the entity."
	case ProvenanceEntityRoleSource:
		return "An entity that is used as input to the activity that produced the target."
	case ProvenanceEntityRoleInstantiates:
		return "The record resulting from this event adheres to the protocol, guideline, order set or other definition represented by this entity."
	case ProvenanceEntityRoleRemoval:
		return "An entity that is removed from accessibility, usually through the DELETE operator."
	}
	return "<unknown>"
}
