// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir500

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// Questionnaire is documented here http://hl7.org/fhir/StructureDefinition/Questionnaire
type Questionnaire struct {
	ID                     *string             `json:"id,omitempty"`
	Meta                   *Meta               `json:"meta,omitempty"`
	ImplicitRules          *string             `json:"implicitRules,omitempty"`
	Language               *string             `json:"language,omitempty"`
	Text                   *Narrative          `json:"text,omitempty"`
	Extension              []Extension         `json:"extension,omitempty"`
	ModifierExtension      []Extension         `json:"modifierExtension,omitempty"`
	Url                    *string             `json:"url,omitempty"`
	Identifier             []Identifier        `json:"identifier,omitempty"`
	Version                *string             `json:"version,omitempty"`
	VersionAlgorithmString *string             `json:"versionAlgorithmString,omitempty"`
	VersionAlgorithmCoding *Coding             `json:"versionAlgorithmCoding,omitempty"`
	Name                   *string             `json:"name,omitempty"`
	Title                  *string             `json:"title,omitempty"`
	DerivedFrom            []string            `json:"derivedFrom,omitempty"`
	Status                 PublicationStatus   `json:"status"`
	Experimental           *bool               `json:"experimental,omitempty"`
	SubjectType            []ResourceType      `json:"subjectType,omitempty"`
	Date                   *string             `json:"date,omitempty"`
	Publisher              *string             `json:"publisher,omitempty"`
	Contact                []ContactDetail     `json:"contact,omitempty"`
	Description            *string             `json:"description,omitempty"`
	UseContext             []UsageContext      `json:"useContext,omitempty"`
	Jurisdiction           []CodeableConcept   `json:"jurisdiction,omitempty"`
	Purpose                *string             `json:"purpose,omitempty"`
	Copyright              *string             `json:"copyright,omitempty"`
	CopyrightLabel         *string             `json:"copyrightLabel,omitempty"`
	ApprovalDate           *string             `json:"approvalDate,omitempty"`
	LastReviewDate         *string             `json:"lastReviewDate,omitempty"`
	EffectivePeriod        *Period             `json:"effectivePeriod,omitempty"`
	Code                   []Coding            `json:"code,omitempty"`
	Item                   []QuestionnaireItem `json:"item,omitempty"`
}
type QuestionnaireItem struct {
	ID                *string                           `json:"id,omitempty"`
	Extension         []Extension                       `json:"extension,omitempty"`
	ModifierExtension []Extension                       `json:"modifierExtension,omitempty"`
	LinkId            string                            `json:"linkId"`
	Definition        *string                           `json:"definition,omitempty"`
	Code              []Coding                          `json:"code,omitempty"`
	Prefix            *string                           `json:"prefix,omitempty"`
	Text              *string                           `json:"text,omitempty"`
	Type              QuestionnaireItemType             `json:"type"`
	EnableWhen        []QuestionnaireItemEnableWhen     `json:"enableWhen,omitempty"`
	EnableBehavior    *EnableWhenBehavior               `json:"enableBehavior,omitempty"`
	DisabledDisplay   *QuestionnaireItemDisabledDisplay `json:"disabledDisplay,omitempty"`
	Required          *bool                             `json:"required,omitempty"`
	Repeats           *bool                             `json:"repeats,omitempty"`
	ReadOnly          *bool                             `json:"readOnly,omitempty"`
	MaxLength         *int                              `json:"maxLength,omitempty"`
	AnswerConstraint  *QuestionnaireAnswerConstraint    `json:"answerConstraint,omitempty"`
	AnswerValueSet    *string                           `json:"answerValueSet,omitempty"`
	AnswerOption      []QuestionnaireItemAnswerOption   `json:"answerOption,omitempty"`
	Initial           []QuestionnaireItemInitial        `json:"initial,omitempty"`
	Item              []QuestionnaireItem               `json:"item,omitempty"`
}
type QuestionnaireItemEnableWhen struct {
	ID                *string                   `json:"id,omitempty"`
	Extension         []Extension               `json:"extension,omitempty"`
	ModifierExtension []Extension               `json:"modifierExtension,omitempty"`
	Question          string                    `json:"question"`
	Operator          QuestionnaireItemOperator `json:"operator"`
	AnswerBoolean     *bool                     `json:"answerBoolean,omitempty"`
	AnswerDecimal     *json.Number              `json:"answerDecimal,omitempty"`
	AnswerInteger     *int                      `json:"answerInteger,omitempty"`
	AnswerDate        *string                   `json:"answerDate,omitempty"`
	AnswerDateTime    *string                   `json:"answerDateTime,omitempty"`
	AnswerTime        *string                   `json:"answerTime,omitempty"`
	AnswerString      *string                   `json:"answerString,omitempty"`
	AnswerCoding      *Coding                   `json:"answerCoding,omitempty"`
	AnswerQuantity    *Quantity                 `json:"answerQuantity,omitempty"`
	AnswerReference   *Reference                `json:"answerReference,omitempty"`
}
type QuestionnaireItemAnswerOption struct {
	ID                *string     `json:"id,omitempty"`
	Extension         []Extension `json:"extension,omitempty"`
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	ValueInteger      *int        `json:"valueInteger,omitempty"`
	ValueDate         *string     `json:"valueDate,omitempty"`
	ValueTime         *string     `json:"valueTime,omitempty"`
	ValueString       *string     `json:"valueString,omitempty"`
	ValueCoding       *Coding     `json:"valueCoding,omitempty"`
	ValueReference    *Reference  `json:"valueReference,omitempty"`
	InitialSelected   *bool       `json:"initialSelected,omitempty"`
}
type QuestionnaireItemInitial struct {
	ID                *string      `json:"id,omitempty"`
	Extension         []Extension  `json:"extension,omitempty"`
	ModifierExtension []Extension  `json:"modifierExtension,omitempty"`
	ValueBoolean      *bool        `json:"valueBoolean,omitempty"`
	ValueDecimal      *json.Number `json:"valueDecimal,omitempty"`
	ValueInteger      *int         `json:"valueInteger,omitempty"`
	ValueDate         *string      `json:"valueDate,omitempty"`
	ValueDateTime     *string      `json:"valueDateTime,omitempty"`
	ValueTime         *string      `json:"valueTime,omitempty"`
	ValueString       *string      `json:"valueString,omitempty"`
	ValueUri          *string      `json:"valueUri,omitempty"`
	ValueAttachment   *Attachment  `json:"valueAttachment,omitempty"`
	ValueCoding       *Coding      `json:"valueCoding,omitempty"`
	ValueQuantity     *Quantity    `json:"valueQuantity,omitempty"`
	ValueReference    *Reference   `json:"valueReference,omitempty"`
}
type OtherQuestionnaire Questionnaire

// MarshalJSON marshals the given Questionnaire as JSON into a byte slice
func (r Questionnaire) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherQuestionnaire
		ResourceType string `json:"resourceType"`
	}{
		OtherQuestionnaire: OtherQuestionnaire(r),
		ResourceType:       "Questionnaire",
	})
}

// UnmarshalQuestionnaire unmarshals a Questionnaire.
func UnmarshalQuestionnaire(b []byte) (Questionnaire, error) {
	var questionnaire Questionnaire
	if err := json.Unmarshal(b, &questionnaire); err != nil {
		return questionnaire, err
	}
	return questionnaire, nil
}
