// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir500

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// RequestOrchestration is documented here http://hl7.org/fhir/StructureDefinition/RequestOrchestration
type RequestOrchestration struct {
	ID                    *string                      `json:"id,omitempty"`
	Meta                  *Meta                        `json:"meta,omitempty"`
	ImplicitRules         *string                      `json:"implicitRules,omitempty"`
	Language              *string                      `json:"language,omitempty"`
	Text                  *Narrative                   `json:"text,omitempty"`
	Extension             []Extension                  `json:"extension,omitempty"`
	ModifierExtension     []Extension                  `json:"modifierExtension,omitempty"`
	Identifier            []Identifier                 `json:"identifier,omitempty"`
	InstantiatesCanonical []string                     `json:"instantiatesCanonical,omitempty"`
	InstantiatesUri       []string                     `json:"instantiatesUri,omitempty"`
	BasedOn               []Reference                  `json:"basedOn,omitempty"`
	Replaces              []Reference                  `json:"replaces,omitempty"`
	GroupIdentifier       *Identifier                  `json:"groupIdentifier,omitempty"`
	Status                RequestStatus                `json:"status"`
	Intent                RequestIntent                `json:"intent"`
	Priority              *RequestPriority             `json:"priority,omitempty"`
	Code                  *CodeableConcept             `json:"code,omitempty"`
	Subject               *Reference                   `json:"subject,omitempty"`
	Encounter             *Reference                   `json:"encounter,omitempty"`
	AuthoredOn            *string                      `json:"authoredOn,omitempty"`
	Author                *Reference                   `json:"author,omitempty"`
	Reason                []CodeableReference          `json:"reason,omitempty"`
	Goal                  []Reference                  `json:"goal,omitempty"`
	Note                  []Annotation                 `json:"note,omitempty"`
	Action                []RequestOrchestrationAction `json:"action,omitempty"`
}
type RequestOrchestrationAction struct {
	ID                  *string                                   `json:"id,omitempty"`
	Extension           []Extension                               `json:"extension,omitempty"`
	ModifierExtension   []Extension                               `json:"modifierExtension,omitempty"`
	LinkId              *string                                   `json:"linkId,omitempty"`
	Prefix              *string                                   `json:"prefix,omitempty"`
	Title               *string                                   `json:"title,omitempty"`
	Description         *string                                   `json:"description,omitempty"`
	TextEquivalent      *string                                   `json:"textEquivalent,omitempty"`
	Priority            *RequestPriority                          `json:"priority,omitempty"`
	Code                []CodeableConcept                         `json:"code,omitempty"`
	Documentation       []RelatedArtifact                         `json:"documentation,omitempty"`
	Goal                []Reference                               `json:"goal,omitempty"`
	Condition           []RequestOrchestrationActionCondition     `json:"condition,omitempty"`
	Input               []RequestOrchestrationActionInput         `json:"input,omitempty"`
	Output              []RequestOrchestrationActionOutput        `json:"output,omitempty"`
	RelatedAction       []RequestOrchestrationActionRelatedAction `json:"relatedAction,omitempty"`
	TimingDateTime      *string                                   `json:"timingDateTime,omitempty"`
	TimingAge           *Age                                      `json:"timingAge,omitempty"`
	TimingPeriod        *Period                                   `json:"timingPeriod,omitempty"`
	TimingDuration      *Duration                                 `json:"timingDuration,omitempty"`
	TimingRange         *Range                                    `json:"timingRange,omitempty"`
	TimingTiming        *Timing                                   `json:"timingTiming,omitempty"`
	Location            *CodeableReference                        `json:"location,omitempty"`
	Participant         []RequestOrchestrationActionParticipant   `json:"participant,omitempty"`
	Type                *CodeableConcept                          `json:"type,omitempty"`
	GroupingBehavior    *ActionGroupingBehavior                   `json:"groupingBehavior,omitempty"`
	SelectionBehavior   *ActionSelectionBehavior                  `json:"selectionBehavior,omitempty"`
	RequiredBehavior    *ActionRequiredBehavior                   `json:"requiredBehavior,omitempty"`
	PrecheckBehavior    *ActionPrecheckBehavior                   `json:"precheckBehavior,omitempty"`
	CardinalityBehavior *ActionCardinalityBehavior                `json:"cardinalityBehavior,omitempty"`
	Resource            *Reference                                `json:"resource,omitempty"`
	DefinitionCanonical *string                                   `json:"definitionCanonical,omitempty"`
	DefinitionUri       *string                                   `json:"definitionUri,omitempty"`
	Transform           *string                                   `json:"transform,omitempty"`
	DynamicValue        []RequestOrchestrationActionDynamicValue  `json:"dynamicValue,omitempty"`
	Action              []RequestOrchestrationAction              `json:"action,omitempty"`
}
type RequestOrchestrationActionCondition struct {
	ID                *string             `json:"id,omitempty"`
	Extension         []Extension         `json:"extension,omitempty"`
	ModifierExtension []Extension         `json:"modifierExtension,omitempty"`
	Kind              ActionConditionKind `json:"kind"`
	Expression        *Expression         `json:"expression,omitempty"`
}
type RequestOrchestrationActionInput struct {
	ID                *string          `json:"id,omitempty"`
	Extension         []Extension      `json:"extension,omitempty"`
	ModifierExtension []Extension      `json:"modifierExtension,omitempty"`
	Title             *string          `json:"title,omitempty"`
	Requirement       *DataRequirement `json:"requirement,omitempty"`
	RelatedData       *string          `json:"relatedData,omitempty"`
}
type RequestOrchestrationActionOutput struct {
	ID                *string          `json:"id,omitempty"`
	Extension         []Extension      `json:"extension,omitempty"`
	ModifierExtension []Extension      `json:"modifierExtension,omitempty"`
	Title             *string          `json:"title,omitempty"`
	Requirement       *DataRequirement `json:"requirement,omitempty"`
	RelatedData       *string          `json:"relatedData,omitempty"`
}
type RequestOrchestrationActionRelatedAction struct {
	ID                *string                 `json:"id,omitempty"`
	Extension         []Extension             `json:"extension,omitempty"`
	ModifierExtension []Extension             `json:"modifierExtension,omitempty"`
	TargetId          string                  `json:"targetId"`
	Relationship      ActionRelationshipType  `json:"relationship"`
	EndRelationship   *ActionRelationshipType `json:"endRelationship,omitempty"`
	OffsetDuration    *Duration               `json:"offsetDuration,omitempty"`
	OffsetRange       *Range                  `json:"offsetRange,omitempty"`
}
type RequestOrchestrationActionParticipant struct {
	ID                *string                `json:"id,omitempty"`
	Extension         []Extension            `json:"extension,omitempty"`
	ModifierExtension []Extension            `json:"modifierExtension,omitempty"`
	Type              *ActionParticipantType `json:"type,omitempty"`
	TypeCanonical     *string                `json:"typeCanonical,omitempty"`
	TypeReference     *Reference             `json:"typeReference,omitempty"`
	Role              *CodeableConcept       `json:"role,omitempty"`
	Function          *CodeableConcept       `json:"function,omitempty"`
	ActorCanonical    *string                `json:"actorCanonical,omitempty"`
	ActorReference    *Reference             `json:"actorReference,omitempty"`
}
type RequestOrchestrationActionDynamicValue struct {
	ID                *string     `json:"id,omitempty"`
	Extension         []Extension `json:"extension,omitempty"`
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	Path              *string     `json:"path,omitempty"`
	Expression        *Expression `json:"expression,omitempty"`
}
type OtherRequestOrchestration RequestOrchestration

// MarshalJSON marshals the given RequestOrchestration as JSON into a byte slice
func (r RequestOrchestration) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherRequestOrchestration
		ResourceType string `json:"resourceType"`
	}{
		OtherRequestOrchestration: OtherRequestOrchestration(r),
		ResourceType:              "RequestOrchestration",
	})
}

// UnmarshalRequestOrchestration unmarshals a RequestOrchestration.
func UnmarshalRequestOrchestration(b []byte) (RequestOrchestration, error) {
	var requestOrchestration RequestOrchestration
	if err := json.Unmarshal(b, &requestOrchestration); err != nil {
		return requestOrchestration, err
	}
	return requestOrchestration, nil
}
