// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir500

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// SupplyRequest is documented here http://hl7.org/fhir/StructureDefinition/SupplyRequest
type SupplyRequest struct {
	ID                 *string                  `json:"id,omitempty"`
	Meta               *Meta                    `json:"meta,omitempty"`
	ImplicitRules      *string                  `json:"implicitRules,omitempty"`
	Language           *string                  `json:"language,omitempty"`
	Text               *Narrative               `json:"text,omitempty"`
	Extension          []Extension              `json:"extension,omitempty"`
	ModifierExtension  []Extension              `json:"modifierExtension,omitempty"`
	Identifier         []Identifier             `json:"identifier,omitempty"`
	Status             *SupplyRequestStatus     `json:"status,omitempty"`
	BasedOn            []Reference              `json:"basedOn,omitempty"`
	Category           *CodeableConcept         `json:"category,omitempty"`
	Priority           *RequestPriority         `json:"priority,omitempty"`
	DeliverFor         *Reference               `json:"deliverFor,omitempty"`
	Item               CodeableReference        `json:"item"`
	Quantity           Quantity                 `json:"quantity"`
	Parameter          []SupplyRequestParameter `json:"parameter,omitempty"`
	OccurrenceDateTime *string                  `json:"occurrenceDateTime,omitempty"`
	OccurrencePeriod   *Period                  `json:"occurrencePeriod,omitempty"`
	OccurrenceTiming   *Timing                  `json:"occurrenceTiming,omitempty"`
	AuthoredOn         *string                  `json:"authoredOn,omitempty"`
	Requester          *Reference               `json:"requester,omitempty"`
	Supplier           []Reference              `json:"supplier,omitempty"`
	Reason             []CodeableReference      `json:"reason,omitempty"`
	DeliverFrom        *Reference               `json:"deliverFrom,omitempty"`
	DeliverTo          *Reference               `json:"deliverTo,omitempty"`
}
type SupplyRequestParameter struct {
	ID                   *string          `json:"id,omitempty"`
	Extension            []Extension      `json:"extension,omitempty"`
	ModifierExtension    []Extension      `json:"modifierExtension,omitempty"`
	Code                 *CodeableConcept `json:"code,omitempty"`
	ValueCodeableConcept *CodeableConcept `json:"valueCodeableConcept,omitempty"`
	ValueQuantity        *Quantity        `json:"valueQuantity,omitempty"`
	ValueRange           *Range           `json:"valueRange,omitempty"`
	ValueBoolean         *bool            `json:"valueBoolean,omitempty"`
}
type OtherSupplyRequest SupplyRequest

// MarshalJSON marshals the given SupplyRequest as JSON into a byte slice
func (r SupplyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherSupplyRequest
		ResourceType string `json:"resourceType"`
	}{
		OtherSupplyRequest: OtherSupplyRequest(r),
		ResourceType:       "SupplyRequest",
	})
}

// UnmarshalSupplyRequest unmarshals a SupplyRequest.
func UnmarshalSupplyRequest(b []byte) (SupplyRequest, error) {
	var supplyRequest SupplyRequest
	if err := json.Unmarshal(b, &supplyRequest); err != nil {
		return supplyRequest, err
	}
	return supplyRequest, nil
}
