// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir500

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// Timing is documented here http://hl7.org/fhir/StructureDefinition/Timing
type Timing struct {
	ID                *string          `json:"id,omitempty"`
	Extension         []Extension      `json:"extension,omitempty"`
	ModifierExtension []Extension      `json:"modifierExtension,omitempty"`
	Event             []string         `json:"event,omitempty"`
	Repeat            *TimingRepeat    `json:"repeat,omitempty"`
	Code              *CodeableConcept `json:"code,omitempty"`
}
type TimingRepeat struct {
	ID             *string      `json:"id,omitempty"`
	Extension      []Extension  `json:"extension,omitempty"`
	BoundsDuration *Duration    `json:"boundsDuration,omitempty"`
	BoundsRange    *Range       `json:"boundsRange,omitempty"`
	BoundsPeriod   *Period      `json:"boundsPeriod,omitempty"`
	Count          *int         `json:"count,omitempty"`
	CountMax       *int         `json:"countMax,omitempty"`
	Duration       *json.Number `json:"duration,omitempty"`
	DurationMax    *json.Number `json:"durationMax,omitempty"`
	DurationUnit   *string      `json:"durationUnit,omitempty"`
	Frequency      *int         `json:"frequency,omitempty"`
	FrequencyMax   *int         `json:"frequencyMax,omitempty"`
	Period         *json.Number `json:"period,omitempty"`
	PeriodMax      *json.Number `json:"periodMax,omitempty"`
	PeriodUnit     *string      `json:"periodUnit,omitempty"`
	DayOfWeek      []DaysOfWeek `json:"dayOfWeek,omitempty"`
	TimeOfDay      []string     `json:"timeOfDay,omitempty"`
	When           []string     `json:"when,omitempty"`
	Offset         *int         `json:"offset,omitempty"`
}
