// Copyright 2019 - 2022 The Samply Community
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fhir500

import "encoding/json"

// THIS FILE IS GENERATED BY https://github.com/samply/golang-fhir-models
// PLEASE DO NOT EDIT BY HAND

// Transport is documented here http://hl7.org/fhir/StructureDefinition/Transport
type Transport struct {
	ID                    *string               `json:"id,omitempty"`
	Meta                  *Meta                 `json:"meta,omitempty"`
	ImplicitRules         *string               `json:"implicitRules,omitempty"`
	Language              *string               `json:"language,omitempty"`
	Text                  *Narrative            `json:"text,omitempty"`
	Extension             []Extension           `json:"extension,omitempty"`
	ModifierExtension     []Extension           `json:"modifierExtension,omitempty"`
	Identifier            []Identifier          `json:"identifier,omitempty"`
	InstantiatesCanonical *string               `json:"instantiatesCanonical,omitempty"`
	InstantiatesUri       *string               `json:"instantiatesUri,omitempty"`
	BasedOn               []Reference           `json:"basedOn,omitempty"`
	GroupIdentifier       *Identifier           `json:"groupIdentifier,omitempty"`
	PartOf                []Reference           `json:"partOf,omitempty"`
	Status                *TransportStatus      `json:"status,omitempty"`
	StatusReason          *CodeableConcept      `json:"statusReason,omitempty"`
	Intent                string                `json:"intent"`
	Priority              *RequestPriority      `json:"priority,omitempty"`
	Code                  *CodeableConcept      `json:"code,omitempty"`
	Description           *string               `json:"description,omitempty"`
	Focus                 *Reference            `json:"focus,omitempty"`
	For                   *Reference            `json:"for,omitempty"`
	Encounter             *Reference            `json:"encounter,omitempty"`
	CompletionTime        *string               `json:"completionTime,omitempty"`
	AuthoredOn            *string               `json:"authoredOn,omitempty"`
	LastModified          *string               `json:"lastModified,omitempty"`
	Requester             *Reference            `json:"requester,omitempty"`
	PerformerType         []CodeableConcept     `json:"performerType,omitempty"`
	Owner                 *Reference            `json:"owner,omitempty"`
	Location              *Reference            `json:"location,omitempty"`
	Insurance             []Reference           `json:"insurance,omitempty"`
	Note                  []Annotation          `json:"note,omitempty"`
	RelevantHistory       []Reference           `json:"relevantHistory,omitempty"`
	Restriction           *TransportRestriction `json:"restriction,omitempty"`
	Input                 []TransportInput      `json:"input,omitempty"`
	Output                []TransportOutput     `json:"output,omitempty"`
	RequestedLocation     Reference             `json:"requestedLocation"`
	CurrentLocation       Reference             `json:"currentLocation"`
	Reason                *CodeableReference    `json:"reason,omitempty"`
	History               *Reference            `json:"history,omitempty"`
}
type TransportRestriction struct {
	ID                *string     `json:"id,omitempty"`
	Extension         []Extension `json:"extension,omitempty"`
	ModifierExtension []Extension `json:"modifierExtension,omitempty"`
	Repetitions       *int        `json:"repetitions,omitempty"`
	Period            *Period     `json:"period,omitempty"`
	Recipient         []Reference `json:"recipient,omitempty"`
}
type TransportInput struct {
	ID                         *string                `json:"id,omitempty"`
	Extension                  []Extension            `json:"extension,omitempty"`
	ModifierExtension          []Extension            `json:"modifierExtension,omitempty"`
	Type                       CodeableConcept        `json:"type"`
	ValueBase64Binary          *string                `json:"valueBase64Binary,omitempty"`
	ValueBoolean               *bool                  `json:"valueBoolean,omitempty"`
	ValueCanonical             *string                `json:"valueCanonical,omitempty"`
	ValueCode                  *string                `json:"valueCode,omitempty"`
	ValueDate                  *string                `json:"valueDate,omitempty"`
	ValueDateTime              *string                `json:"valueDateTime,omitempty"`
	ValueDecimal               *json.Number           `json:"valueDecimal,omitempty"`
	ValueId                    *string                `json:"valueId,omitempty"`
	ValueInstant               *string                `json:"valueInstant,omitempty"`
	ValueInteger               *int                   `json:"valueInteger,omitempty"`
	ValueInteger64             *string                `json:"valueInteger64,omitempty"`
	ValueMarkdown              *string                `json:"valueMarkdown,omitempty"`
	ValueOid                   *string                `json:"valueOid,omitempty"`
	ValuePositiveInt           *int                   `json:"valuePositiveInt,omitempty"`
	ValueString                *string                `json:"valueString,omitempty"`
	ValueTime                  *string                `json:"valueTime,omitempty"`
	ValueUnsignedInt           *int                   `json:"valueUnsignedInt,omitempty"`
	ValueUri                   *string                `json:"valueUri,omitempty"`
	ValueUrl                   *string                `json:"valueUrl,omitempty"`
	ValueUuid                  *string                `json:"valueUuid,omitempty"`
	ValueAddress               *Address               `json:"valueAddress,omitempty"`
	ValueAge                   *Age                   `json:"valueAge,omitempty"`
	ValueAnnotation            *Annotation            `json:"valueAnnotation,omitempty"`
	ValueAttachment            *Attachment            `json:"valueAttachment,omitempty"`
	ValueCodeableConcept       *CodeableConcept       `json:"valueCodeableConcept,omitempty"`
	ValueCodeableReference     *CodeableReference     `json:"valueCodeableReference,omitempty"`
	ValueCoding                *Coding                `json:"valueCoding,omitempty"`
	ValueContactPoint          *ContactPoint          `json:"valueContactPoint,omitempty"`
	ValueCount                 *Count                 `json:"valueCount,omitempty"`
	ValueDistance              *Distance              `json:"valueDistance,omitempty"`
	ValueDuration              *Duration              `json:"valueDuration,omitempty"`
	ValueHumanName             *HumanName             `json:"valueHumanName,omitempty"`
	ValueIdentifier            *Identifier            `json:"valueIdentifier,omitempty"`
	ValueMoney                 *Money                 `json:"valueMoney,omitempty"`
	ValuePeriod                *Period                `json:"valuePeriod,omitempty"`
	ValueQuantity              *Quantity              `json:"valueQuantity,omitempty"`
	ValueRange                 *Range                 `json:"valueRange,omitempty"`
	ValueRatio                 *Ratio                 `json:"valueRatio,omitempty"`
	ValueRatioRange            *RatioRange            `json:"valueRatioRange,omitempty"`
	ValueReference             *Reference             `json:"valueReference,omitempty"`
	ValueSampledData           *SampledData           `json:"valueSampledData,omitempty"`
	ValueSignature             *Signature             `json:"valueSignature,omitempty"`
	ValueTiming                *Timing                `json:"valueTiming,omitempty"`
	ValueContactDetail         *ContactDetail         `json:"valueContactDetail,omitempty"`
	ValueDataRequirement       *DataRequirement       `json:"valueDataRequirement,omitempty"`
	ValueExpression            *Expression            `json:"valueExpression,omitempty"`
	ValueParameterDefinition   *ParameterDefinition   `json:"valueParameterDefinition,omitempty"`
	ValueRelatedArtifact       *RelatedArtifact       `json:"valueRelatedArtifact,omitempty"`
	ValueTriggerDefinition     *TriggerDefinition     `json:"valueTriggerDefinition,omitempty"`
	ValueUsageContext          *UsageContext          `json:"valueUsageContext,omitempty"`
	ValueAvailability          *Availability          `json:"valueAvailability,omitempty"`
	ValueExtendedContactDetail *ExtendedContactDetail `json:"valueExtendedContactDetail,omitempty"`
	ValueDosage                *Dosage                `json:"valueDosage,omitempty"`
	ValueMeta                  *Meta                  `json:"valueMeta,omitempty"`
}
type TransportOutput struct {
	ID                         *string                `json:"id,omitempty"`
	Extension                  []Extension            `json:"extension,omitempty"`
	ModifierExtension          []Extension            `json:"modifierExtension,omitempty"`
	Type                       CodeableConcept        `json:"type"`
	ValueBase64Binary          *string                `json:"valueBase64Binary,omitempty"`
	ValueBoolean               *bool                  `json:"valueBoolean,omitempty"`
	ValueCanonical             *string                `json:"valueCanonical,omitempty"`
	ValueCode                  *string                `json:"valueCode,omitempty"`
	ValueDate                  *string                `json:"valueDate,omitempty"`
	ValueDateTime              *string                `json:"valueDateTime,omitempty"`
	ValueDecimal               *json.Number           `json:"valueDecimal,omitempty"`
	ValueId                    *string                `json:"valueId,omitempty"`
	ValueInstant               *string                `json:"valueInstant,omitempty"`
	ValueInteger               *int                   `json:"valueInteger,omitempty"`
	ValueInteger64             *string                `json:"valueInteger64,omitempty"`
	ValueMarkdown              *string                `json:"valueMarkdown,omitempty"`
	ValueOid                   *string                `json:"valueOid,omitempty"`
	ValuePositiveInt           *int                   `json:"valuePositiveInt,omitempty"`
	ValueString                *string                `json:"valueString,omitempty"`
	ValueTime                  *string                `json:"valueTime,omitempty"`
	ValueUnsignedInt           *int                   `json:"valueUnsignedInt,omitempty"`
	ValueUri                   *string                `json:"valueUri,omitempty"`
	ValueUrl                   *string                `json:"valueUrl,omitempty"`
	ValueUuid                  *string                `json:"valueUuid,omitempty"`
	ValueAddress               *Address               `json:"valueAddress,omitempty"`
	ValueAge                   *Age                   `json:"valueAge,omitempty"`
	ValueAnnotation            *Annotation            `json:"valueAnnotation,omitempty"`
	ValueAttachment            *Attachment            `json:"valueAttachment,omitempty"`
	ValueCodeableConcept       *CodeableConcept       `json:"valueCodeableConcept,omitempty"`
	ValueCodeableReference     *CodeableReference     `json:"valueCodeableReference,omitempty"`
	ValueCoding                *Coding                `json:"valueCoding,omitempty"`
	ValueContactPoint          *ContactPoint          `json:"valueContactPoint,omitempty"`
	ValueCount                 *Count                 `json:"valueCount,omitempty"`
	ValueDistance              *Distance              `json:"valueDistance,omitempty"`
	ValueDuration              *Duration              `json:"valueDuration,omitempty"`
	ValueHumanName             *HumanName             `json:"valueHumanName,omitempty"`
	ValueIdentifier            *Identifier            `json:"valueIdentifier,omitempty"`
	ValueMoney                 *Money                 `json:"valueMoney,omitempty"`
	ValuePeriod                *Period                `json:"valuePeriod,omitempty"`
	ValueQuantity              *Quantity              `json:"valueQuantity,omitempty"`
	ValueRange                 *Range                 `json:"valueRange,omitempty"`
	ValueRatio                 *Ratio                 `json:"valueRatio,omitempty"`
	ValueRatioRange            *RatioRange            `json:"valueRatioRange,omitempty"`
	ValueReference             *Reference             `json:"valueReference,omitempty"`
	ValueSampledData           *SampledData           `json:"valueSampledData,omitempty"`
	ValueSignature             *Signature             `json:"valueSignature,omitempty"`
	ValueTiming                *Timing                `json:"valueTiming,omitempty"`
	ValueContactDetail         *ContactDetail         `json:"valueContactDetail,omitempty"`
	ValueDataRequirement       *DataRequirement       `json:"valueDataRequirement,omitempty"`
	ValueExpression            *Expression            `json:"valueExpression,omitempty"`
	ValueParameterDefinition   *ParameterDefinition   `json:"valueParameterDefinition,omitempty"`
	ValueRelatedArtifact       *RelatedArtifact       `json:"valueRelatedArtifact,omitempty"`
	ValueTriggerDefinition     *TriggerDefinition     `json:"valueTriggerDefinition,omitempty"`
	ValueUsageContext          *UsageContext          `json:"valueUsageContext,omitempty"`
	ValueAvailability          *Availability          `json:"valueAvailability,omitempty"`
	ValueExtendedContactDetail *ExtendedContactDetail `json:"valueExtendedContactDetail,omitempty"`
	ValueDosage                *Dosage                `json:"valueDosage,omitempty"`
	ValueMeta                  *Meta                  `json:"valueMeta,omitempty"`
}
type OtherTransport Transport

// MarshalJSON marshals the given Transport as JSON into a byte slice
func (r Transport) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		OtherTransport
		ResourceType string `json:"resourceType"`
	}{
		OtherTransport: OtherTransport(r),
		ResourceType:   "Transport",
	})
}

// UnmarshalTransport unmarshals a Transport.
func UnmarshalTransport(b []byte) (Transport, error) {
	var transport Transport
	if err := json.Unmarshal(b, &transport); err != nil {
		return transport, err
	}
	return transport, nil
}
