
package fhir430

import (
	"encoding/json"
	"fmt"
	"strings"
)
// DocumentRelationshipType is documented here http://hl7.org/fhir/ValueSet/document-relationship-type
type DocumentRelationshipType int

const (
	DocumentRelationshipTypeReplaces DocumentRelationshipType = iota
	DocumentRelationshipTypeTransforms
	DocumentRelationshipTypeSigns
	DocumentRelationshipTypeAppends
)

func (code DocumentRelationshipType) MarshalJSON() ([]byte, error) {
	return json.Marshal(code.Code())
}
func (code *DocumentRelationshipType) UnmarshalJSON(input []byte) error {
	var s string
	if err := json.Unmarshal(input, &s); err != nil {
		return fmt.Errorf("failed to Unmarshal DocumentRelationshipType code `%s`", s)
	}
	s = strings.ToLower(s)
	switch s {
	case "replaces":
		*code = DocumentRelationshipTypeReplaces
	case "transforms":
		*code = DocumentRelationshipTypeTransforms
	case "signs":
		*code = DocumentRelationshipTypeSigns
	case "appends":
		*code = DocumentRelationshipTypeAppends
	default:
		return fmt.Errorf("unknown DocumentRelationshipType code `%s`", s)
	}
	return nil
}
func (code DocumentRelationshipType) String() string {
	return code.Code()
}
func (code DocumentRelationshipType) Code() string {
	switch code {
	case DocumentRelationshipTypeReplaces:
		return "replaces"
	case DocumentRelationshipTypeTransforms:
		return "transforms"
	case DocumentRelationshipTypeSigns:
		return "signs"
	case DocumentRelationshipTypeAppends:
		return "appends"
	}
	return "<unknown>"
}
func (code DocumentRelationshipType) Display() string {
	switch code {
	case DocumentRelationshipTypeReplaces:
		return "Replaces"
	case DocumentRelationshipTypeTransforms:
		return "Transforms"
	case DocumentRelationshipTypeSigns:
		return "Signs"
	case DocumentRelationshipTypeAppends:
		return "Appends"
	}
	return "<unknown>"
}
func (code DocumentRelationshipType) Definition() string {
	switch code {
	case DocumentRelationshipTypeReplaces:
		return "This document logically replaces or supersedes the target document."
	case DocumentRelationshipTypeTransforms:
		return "This document was generated by transforming the target document (e.g. format or language conversion)."
	case DocumentRelationshipTypeSigns:
		return "This document is a signature of the target document."
	case DocumentRelationshipTypeAppends:
		return "This document adds additional information to the target document."
	}
	return "<unknown>"
}
